### ISSUE TITLE
Error on frontend when displaying only one item

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#1283]
Error on frontend when displaying only one item.

Error : "d.ldp:contains.map is not a function"
![image](https://github.com/assemblee-virtuelle/semapps/assets/6891994/71a92b9e-5eb9-4175-8c3c-5022677a4160)

If I add 2 items (organization or other items), they can be displayed.

**Comment by mguihal** [comment]
Hello 👋

Isn't it resolved in this release https://github.com/assemblee-virtuelle/semapps/releases/tag/frontend-v0.6.2?
You tested it on Archipelago which uses v0.6.0 of semantic-data-provider.   
This issue should be resolved in the next upgrade :)

**Comment by fluidlog** [comment]
Merci @mguihal et merci @srosset81, je vais tester ça dans les prochains jours, si ça fonctionne, je fermerai cette issue :)

**Comment by fluidlog** [comment]
Are you OK to switch Archipelago 2.0 using 0.6.6 frontend version ?
I test it before...

**Comment by fluidlog** [comment]
I just see that @mguihal did the migration in 0.6.5 here yesterday... :)
https://github.com/assemblee-virtuelle/archipelago/pull/186
Do you want to create a tag 2.0.1 in order that we have juste to update Dockerfile to this new tag to get the upgrade ?
Thanks !

**Comment by mguihal** [comment]
I released a v2.1.0 of Archipelago here: https://github.com/assemblee-virtuelle/archipelago/releases/tag/v2.1.0

**Comment by fluidlog** [comment]
@mguihal On last Friday, I try to rebuilt my server using 2.1.0 version, and I experiment some problem with : 
![image](https://github.com/user-attachments/assets/80b4a77a-259c-40cb-a855-68080e5148e5)

So, I remove member tab while waiting to understand

After, I experiment problem with frontend.

![image](https://github.com/user-attachments/assets/1831d965-49db-4110-b4b9-cb0c662b95dc)

![image](https://github.com/user-attachments/assets/7eefa86d-f8c8-4672-a4e3-74a75bbc0956)

My question is : "do you test 2.1.0 with Nantes Archipelago AddOn" (which is my reference) ?

**Comment by mguihal** [comment]
Your errors come from customized files from your instance (in particular OrganizationEdit) that has changed between two versions. Please be conscious that upgrading Archipelago may contains such changes and you have to replicate on your files if you have customized them. Second error is due to new resource that doesn't have dataModel.list parameters, and your customized code requires it.

If you are based on "Transiscope Nantes" Archipelago instance and you don't want to maintain this customized code, you can wait for this instance to be updated and copy it. (Actually it was updated since yesterday)

Versions of Archipelago are fully tested on raw basecode only. Maintainers of customized instances have to update and test their own overridden code.

**Comment by fluidlog** [comment]
Thank you, I succed in use 2.1.0 for my project, using your update on Nantes project.
It correct this issue, so we can close it.
