### ISSUE TITLE
Prevent compaction script from failing

### ISSUE THREAD

**Issue by Laurin-W** [assemblee-virtuelle/semapps#1305]
Sometimes compaction fails which stops the whole cron job script and has caused the disk running full before.
Handling failures, possibly with a wait and retry, and continuing the execution of the remaining datasets, should patch it for now. In the mid-term we are migrating away from the fuseki ACL extension, so duckt-taping is okay.

The script to modify: https://github.com/assemblee-virtuelle/semapps/blob/master/src/jena/fuseki-docker/docker-compact-entrypoint.sh

**Comment by srosset81** [comment]
One important thing to note: if the compaction fails (for example due to lack of space), the new folder with data (for example `/Data-35`) may contain no data. In that case, it's important to delete this new folder (`/Data-35`), otherwise when the script will go through the second part (deleting all old data), it will delete the correct folder and keep the empty one.

**Comment by srosset81** [comment]
Fixed here https://github.com/assemblee-virtuelle/semapps/commit/fd441da56b2b47217b215be8347e4a289d7ee96d
